//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TestAppDotnetFramawork.ResultNew {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="YNE_WS_MTBKT_RESULT_NEW", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YNE_WS_MTBKT_RESULT_NEW : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback YneMtbktResultNewOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public YNE_WS_MTBKT_RESULT_NEW() {
            this.Url = global::TestAppDotnetFramawork.Properties.Settings.Default.TestAppDotnetFramawork_ResultNew_YNE_WS_MTBKT_RESULT_NEW;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event YneMtbktResultNewCompletedEventHandler YneMtbktResultNewCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:YNE_WS_MTBKT_RESULT_NEW:YneMtbkt" +
            "ResultNewRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("YneMtbktResultNewResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public YneMtbktResultNewResponse YneMtbktResultNew([System.Xml.Serialization.XmlElementAttribute("YneMtbktResultNew", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] YneMtbktResultNew YneMtbktResultNew1) {
            object[] results = this.Invoke("YneMtbktResultNew", new object[] {
                        YneMtbktResultNew1});
            return ((YneMtbktResultNewResponse)(results[0]));
        }
        
        /// <remarks/>
        public void YneMtbktResultNewAsync(YneMtbktResultNew YneMtbktResultNew1) {
            this.YneMtbktResultNewAsync(YneMtbktResultNew1, null);
        }
        
        /// <remarks/>
        public void YneMtbktResultNewAsync(YneMtbktResultNew YneMtbktResultNew1, object userState) {
            if ((this.YneMtbktResultNewOperationCompleted == null)) {
                this.YneMtbktResultNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYneMtbktResultNewOperationCompleted);
            }
            this.InvokeAsync("YneMtbktResultNew", new object[] {
                        YneMtbktResultNew1}, this.YneMtbktResultNewOperationCompleted, userState);
        }
        
        private void OnYneMtbktResultNewOperationCompleted(object arg) {
            if ((this.YneMtbktResultNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YneMtbktResultNewCompleted(this, new YneMtbktResultNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YneMtbktResultNew {
        
        private string iAnswerField;
        
        private string iFile_1Field;
        
        private string iFile_2Field;
        
        private string iIpField;
        
        private string iNoDataField;
        
        private string iRandidField;
        
        private string iRpmailField;
        
        private string iSprasField;
        
        private string iTerminalField;
        
        private string iTextField;
        
        private string iUnvanField;
        
        private string iUserField;
        
        private YneMtbktSBformSf isBformField;
        
        private YneMtbktSKformSf isKformField;
        
        private YneMtbktSCformSf[] itCformField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IAnswer {
            get {
                return this.iAnswerField;
            }
            set {
                this.iAnswerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IFile_1 {
            get {
                return this.iFile_1Field;
            }
            set {
                this.iFile_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IFile_2 {
            get {
                return this.iFile_2Field;
            }
            set {
                this.iFile_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IIp {
            get {
                return this.iIpField;
            }
            set {
                this.iIpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INoData {
            get {
                return this.iNoDataField;
            }
            set {
                this.iNoDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IRandid {
            get {
                return this.iRandidField;
            }
            set {
                this.iRandidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IRpmail {
            get {
                return this.iRpmailField;
            }
            set {
                this.iRpmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISpras {
            get {
                return this.iSprasField;
            }
            set {
                this.iSprasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITerminal {
            get {
                return this.iTerminalField;
            }
            set {
                this.iTerminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IText {
            get {
                return this.iTextField;
            }
            set {
                this.iTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IUnvan {
            get {
                return this.iUnvanField;
            }
            set {
                this.iUnvanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IUser {
            get {
                return this.iUserField;
            }
            set {
                this.iUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YneMtbktSBformSf IsBform {
            get {
                return this.isBformField;
            }
            set {
                this.isBformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YneMtbktSKformSf IsKform {
            get {
                return this.isKformField;
            }
            set {
                this.isKformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public YneMtbktSCformSf[] ItCform {
            get {
                return this.itCformField;
            }
            set {
                this.itCformField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YneMtbktSBformSf {
        
        private decimal baseBaField;
        
        private int countBaField;
        
        private decimal baseBsField;
        
        private int countBsField;
        
        private decimal tvbasField;
        
        private decimal tvsteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BaseBa {
            get {
                return this.baseBaField;
            }
            set {
                this.baseBaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CountBa {
            get {
                return this.countBaField;
            }
            set {
                this.countBaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BaseBs {
            get {
                return this.baseBsField;
            }
            set {
                this.baseBsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CountBs {
            get {
                return this.countBsField;
            }
            set {
                this.countBsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Tvbas {
            get {
                return this.tvbasField;
            }
            set {
                this.tvbasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Tvste {
            get {
                return this.tvsteField;
            }
            set {
                this.tvsteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YneMtbktSCformSf {
        
        private string xsumField;
        
        private string ltextField;
        
        private string akontField;
        
        private decimal dmbtrField;
        
        private decimal wrbtrField;
        
        private string waersField;
        
        private decimal kursfField;
        
        private string debitCreditField;
        
        private decimal dmbtrCField;
        
        private decimal wrbtrCField;
        
        private string waersCField;
        
        private string cariField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Xsum {
            get {
                return this.xsumField;
            }
            set {
                this.xsumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ltext {
            get {
                return this.ltextField;
            }
            set {
                this.ltextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Akont {
            get {
                return this.akontField;
            }
            set {
                this.akontField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Dmbtr {
            get {
                return this.dmbtrField;
            }
            set {
                this.dmbtrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Wrbtr {
            get {
                return this.wrbtrField;
            }
            set {
                this.wrbtrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Waers {
            get {
                return this.waersField;
            }
            set {
                this.waersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Kursf {
            get {
                return this.kursfField;
            }
            set {
                this.kursfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DebitCredit {
            get {
                return this.debitCreditField;
            }
            set {
                this.debitCreditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal DmbtrC {
            get {
                return this.dmbtrCField;
            }
            set {
                this.dmbtrCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WrbtrC {
            get {
                return this.wrbtrCField;
            }
            set {
                this.wrbtrCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WaersC {
            get {
                return this.waersCField;
            }
            set {
                this.waersCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cari {
            get {
                return this.cariField;
            }
            set {
                this.cariField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YneMtbktSKformSf {
        
        private int tevkCountBsField;
        
        private decimal tevkBaseBsField;
        
        private decimal tevkCurrBsField;
        
        private int tevkCountBaField;
        
        private decimal tevkBaseBaField;
        
        private decimal tevkCurrBaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TevkCountBs {
            get {
                return this.tevkCountBsField;
            }
            set {
                this.tevkCountBsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TevkBaseBs {
            get {
                return this.tevkBaseBsField;
            }
            set {
                this.tevkBaseBsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TevkCurrBs {
            get {
                return this.tevkCurrBsField;
            }
            set {
                this.tevkCurrBsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TevkCountBa {
            get {
                return this.tevkCountBaField;
            }
            set {
                this.tevkCountBaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TevkBaseBa {
            get {
                return this.tevkBaseBaField;
            }
            set {
                this.tevkBaseBaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TevkCurrBa {
            get {
                return this.tevkCurrBaField;
            }
            set {
                this.tevkCurrBaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class YneMtbktResultNewResponse {
        
        private string eTextField;
        
        private YneMtbktSCformSf[] etCformField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EText {
            get {
                return this.eTextField;
            }
            set {
                this.eTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public YneMtbktSCformSf[] EtCform {
            get {
                return this.etCformField;
            }
            set {
                this.etCformField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void YneMtbktResultNewCompletedEventHandler(object sender, YneMtbktResultNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YneMtbktResultNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YneMtbktResultNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YneMtbktResultNewResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YneMtbktResultNewResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591